In [2]:
!pip install obp

  Using cached obp-0.5.7.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Pillow-9.1.1.tar.gz (49.8 MB)
  Preparing metadata (setup.py) ... done
  Using cached PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
  Using cached mypy_extensions-0.4.4-py2.py3-none-any.whl
  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
  Using cached pandas-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Using cached pingouin-0.4.0.tar.gz (206 kB)
  Preparing metadata (setup.py) ... done
  Using cached pyieoe-0.1.1.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
  Using cached scikit_learn-1.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
  Using cached scipy-1.9.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.m

In [3]:
import obp
from obp.dataset import OpenBanditDataset

ModuleNotFoundError: No module named 'obp'

In [ ]:
# obp version
print(obp.__version__)

0.5.7


In [4]:
from obp.simulator.simulator import BanditEnvironmentSimulator, BanditPolicySimulator
from obp.dataset import logistic_sparse_reward_function

In [35]:
dataset = OpenBanditDataset(behavior_policy="bts", campaign="all")

INFO:obp.dataset.real:When `data_path` is not given, this class downloads the small-sized version of Open Bandit Dataset.


In [36]:
data_dict = dataset.obtain_batch_bandit_feedback()

In [37]:
data_dict.keys()

dict_keys(['n_rounds', 'n_actions', 'action', 'position', 'reward', 'pscore', 'context', 'action_context'])

In [46]:
data_dict['action'][-30:]

array([19, 41, 60, 60, 61, 45, 47, 58, 61,  8, 39, 47, 51, 41,  7, 43,  1,
       59,  3, 43, 41, 18,  7,  7, 39, 35, 60, 52, 39, 35])

In [47]:
data_dict['position'][-30:]

array([1, 2, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 2, 0, 0, 1, 2,
       1, 2, 2, 0, 0, 2, 2, 2])

In [48]:
data_dict['pscore'][-30:]

array([0.002455, 0.047465, 0.068955, 0.041455, 0.053745, 0.022405,
       0.09077 , 0.06299 , 0.042735, 0.024285, 0.08808 , 0.052475,
       0.02205 , 0.03372 , 0.169115, 0.03343 , 0.01746 , 0.095   ,
       0.02189 , 0.025965, 0.01335 , 0.05156 , 0.157015, 0.11955 ,
       0.1076  , 0.020135, 0.03303 , 0.00136 , 0.09762 , 0.031415])

In [51]:
sum(data_dict['reward'])

42

In [52]:
len(data_dict['reward'])

10000

In [33]:
dataset.load_raw_data()

In [34]:
dataset.data

timestamp  item_id  position  click  \
0     2019-11-24 00:00:34.762830+00:00       14         3      0   
1     2019-11-24 00:00:53.965051+00:00       14         3      0   
2     2019-11-24 00:00:56.727734+00:00       27         3      0   
3     2019-11-24 00:02:17.189232+00:00       48         2      0   
4     2019-11-24 00:03:02.129117+00:00       36         2      0   
...                                ...      ...       ...    ...   
9995  2019-11-30 23:54:00.176333+00:00        2         2      0   
9996  2019-11-30 23:56:33.056370+00:00       45         2      0   
9997  2019-11-30 23:56:56.226438+00:00       32         3      0   
9998  2019-11-30 23:59:00.464926+00:00       13         2      0   
9999  2019-11-30 23:59:47.022892+00:00       47         1      0   

      propensity_score                    user_feature_0  \
0               0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
1               0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
2               0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
3               0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
4               0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
...                ...                               ...   
9995            0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
9996            0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
9997            0.0125  cef3390ed299c09874189c387777674a   
9998            0.0125  81ce123cbb5bd8ce818f60fb3586bba5   
9999            0.0125  cef3390ed299c09874189c387777674a   

                        user_feature_1                    user_feature_2  \
0     03a5648a76832f83c859d46bc06cb64a  c2e4f76cdbabecd33b8c762aeef386b3   
1     03a5648a76832f83c859d46bc06cb64a  2723d2eb8bba04e0362098011fa3997b   
2     03a5648a76832f83c859d46bc06cb64a  9b2d331c329ceb74d3dcfb48d8798c78   
3     03a5648a76832f83c859d46bc06cb64a  2723d2eb8bba04e0362098011fa3997b   
4     03a5648a76832f83c859d46bc06cb64a  c2e4f76cdbabecd33b8c762aeef386b3   
...                                ...                               ...   
9995  03a5648a76832f83c859d46bc06cb64a  2723d2eb8bba04e0362098011fa3997b   
9996  03a5648a76832f83c859d46bc06cb64a  719dab53a7560218a9d1f96b25d6fa32   
9997  2d03db5543b14483e52d761760686b64  2723d2eb8bba04e0362098011fa3997b   
9998  03a5648a76832f83c859d46bc06cb64a  7bc94a2da491829b777c49c4b5e480f2   
9999  03a5648a76832f83c859d46bc06cb64a  2723d2eb8bba04e0362098011fa3997b   

                        user_feature_3  user-item_affinity_0  ...  \
0     f97571b9c14a786aab269f0b427d2a85                   0.0  ...   
1     c39b0c7dd5d4eb9a18e7db6ba2f258f8                   0.0  ...   
2     270b3e1c052b4f2e9c90bf0ebeb84f34                   0.0  ...   
3     c39b0c7dd5d4eb9a18e7db6ba2f258f8                   0.0  ...   
4     f97571b9c14a786aab269f0b427d2a85                   0.0  ...   
...                                ...                   ...  ...   
9995  c39b0c7dd5d4eb9a18e7db6ba2f258f8                   0.0  ...   
9996  c39b0c7dd5d4eb9a18e7db6ba2f258f8                   0.0  ...   
9997  f97571b9c14a786aab269f0b427d2a85                   0.0  ...   
9998  9bde591ffaab8d54c457448e4dca6f53                   0.0  ...   
9999  06128286bcc64b6a4b0fb7bc0328fe17                   0.0  ...   

      user-item_affinity_70  user-item_affinity_71  user-item_affinity_72  \
0                       0.0                    0.0                    0.0   
1                       0.0                    0.0                    0.0   
2                       0.0                    1.0                    0.0   
3                       0.0                    0.0                    0.0   
4                       0.0                    0.0                    0.0   
...                     ...                    ...                    ...   
9995                    0.0                    0.0                    0.0   
9996                    0.0                    0.0                    0.0   
9997                    0.0                    0.0      

In [14]:


for n_rounds in experiment_round_size:
    for experiment in range(n_runs_per_round_size):
        training_bandit_batch = env.next_bandit_round_batch(n_rounds=n_rounds)
        print(training_bandit_batch)
        break

BanditRounds(n_rounds=1, n_actions=100, context=array([[-0.20470766]]), action_context=array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]]), rewards=array([[0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1]]), expected_rewards=array([[9.03928491e-03, 9.91028197e-01, 9.34047508e-01, 4.55133958e-01,
        4.46661881e-01, 6.29522063e-02, 5.70690551e-01, 8.85728049e-01,
        9.96723238e-01, 4.74284430e-01, 9.96345349e-01, 8.73264872e-01,
        4.46661881e-01, 9.81492077e-01, 4.46661881e-01, 8.58176753e-01,
        7.47937956e-01, 9.99813771e-01, 9.61845186e